#!/bin/sh

# script for execution of rgnuplotx.
exe_name=$0
exe_dir=`dirname $0`
cd $exe_dir

# Look for gnuplot in the execution directory. rgnuplotx is just my name for gnuplotx provided by fink.
./rgnuplotx "$@"
